### ISSUE TITLE
FEEDBACK REQUESTED: Stakeholder Qs

### ISSUE THREAD

**Issue by owenjoseph** [hackforla/shared-housing#10]
### Feedback Request
Please read through them and add any comments they might have so we can be all set for interviewing both the Navigation and Housing Location teams:

https://hackmd.io/-F01ondTTJqgJWFhs4ypOA

### Resources/Instructions
Feedback open until card is closed

**Comment by owenjoseph** [comment]
@awadethomas I'm trying something out for issues where feedback is being solicited from the team at large. As the owner you can move this card to done to signal feedback is closed.

**Comment by awadethomas** [comment]
@owenjoseph we still haven't gotten anything from these, but seeing as how we want to add more 'humanizing' questions moving forward, should we repurpose?

**Comment by awadethomas** [comment]
## Humanizing questions

**General**
- Where do you live?
- What is the highest level of education you've has received?
- How much work experience do you have?
- How comfortable are you with using technology?
- What technological devices do you use on a regular basis?
- What software and/or applications do you use on a regular basis?
- How much time do you spend browsing the web every day?
- Can you describe how you spend a typical day or week outside of work?

**Domain Knowledge**
- What skills are required to do your job?
- How do you stay up to date and get information on your industry and profession?

**Goals**
- What are your responsibilities in your job?
- How do you define progress or success in your job?
- How do you measure progress or success?

**Motivation/Attitude**
- Why do you work for this company and not another?
- What are the most enjoyable parts of your job?
- What do you value most?

**Process**
- Describe a typical workday. What do you do when you first get into the office? What do you do next?
- What activities take up most of your time?
- What activities are most important to your success?
- What processes have you developed on your own?
- Have you learned to work better from your colleagues?

**Environment** - (if we are in house we can have them show us)
- How is your office organized to help you accomplish your tasks or goals?

**Pain Points**
- What are the most difficult, challenging, annoying or frustrating aspects of your job?
- After a typical workday, what about your job (if anything) is still on your mind? (In other words, what issues keep you up at night?)

**Comment by chuderek** [comment]
Hello All, 

I think that this is an awesome set of questions that we can use. Attached, is some suggestions I have.
 
[Humanizing questions- feedback.docx](https://github.com/hackforla/shared-housing/files/3379207/Humanizing.questions-.feedback.docx)

**Comment by owenjoseph** [comment]
Just putting some of @chuderek 's additional Qs here for visibility:

- What do you value most in your job? (You could ask what are your values in the general section.)
- What motivates you at work?
- How do you stay motivated?
- What is the highest level of education you have received?
- What are your hobbies?

**Comment by AlexChh93** [comment]
[Humanizing Questions Comments.docx](https://github.com/hackforla/shared-housing/files/3403775/Humanizing.Questions.Comments.docx)

**Comment by awadethomas** [comment]
Alright, we should be able to loop these in and be ready for upcoming interviews!

**Comment by awadethomas** [comment]
## Humanizing questions

**General**
- Where do you live?
- What are your hobbies?
- What is the highest level of education you've has received?
- How much work experience do you have?
- How comfortable are you with using technology?
- What technological devices do you use on a regular basis?
- What software and/or applications do you use on a regular basis?
- How much time do you spend browsing the web every day?
- Can you describe how you spend a typical day or week outside of work?

**Domain Knowledge**
- What skills are required to do your job?
- How do you stay up to date and get information on your industry and profession?

**Goals**
- What are your responsibilities in your job?
- How do you define progress or success in your job?
- How do you measure progress or success?

**Motivation/Attitude**
- Why do you work for this company and not another?
- What are the most enjoyable parts of your job?
- Could you tell me about the most enjoyable experience you had with LAFH?
- What do you value most?
- What motivates you at work?
- How do you stay motivated?

**Process**
- Describe a typical workday. What do you do when you first get into the office? What do you do next?
- What activities take up most of your time?
- What activities are most important to your success?
- What processes have you developed on your own?
- Has your process changed since you started at LAFH? How?
- Have you learned to work better from your colleagues?

**Environment** - (if we are in house we can have them show us)
- How is your office organized to help you accomplish your tasks or goals?

**Pain Points**
- What are the most difficult, challenging, annoying or frustrating aspects of your job?
- After a typical workday, what about your job (if anything) is still on your mind? (In other words, what issues keep you up at night?)
- If you could change anything within LAFH Shared Housing project, what would it be and why?

**Comment by awadethomas** [comment]
I went ahead and finalized the questions with all of the comments - see above and let me know if we're missing anything
* For context, they are intended for 30-40 minute interviews

**Comment by awadethomas** [comment]
We can close this one - I added a final draft to the shared folder
