### ISSUE TITLE
Fix frontend routing issue when user refreshes

### ISSUE THREAD

**Issue by kkchu791** [hackforla/shared-housing#184]
### Overview

Bug: Currently, when user navigates to a different route (ie /Dashboard), and then refreshes, the page does not rerender the content. 

Acceptance case: When user refreshes the page on a different route (ie /Dashboard), it should show the content of the webpage he was on.

**Comment by tylerthome** [comment]
In case this is referring to our "production" build ( i.e. Flask): this probably falls to the backend team to forward all non-API routes down to index.html -- React Router handles the URL pretty well out of the box in my experience. 

Then front-end would need to make sure that no "reloadable" pages are depending on props.location.state in any way that breaks things, because that won't be there unless we do some weird unnecessary hacks. Looks like you guys are already well with your useFetch/useAPI set up. 

For example: if user reloads on page /customer/5/responses, my assumption is this:

1. browser request "/candidate/5/responses"
2. flask recognizes non-API route, forward to client
3. react router render "/candidate/:id/responses"
4. ResponseListView component useEffect calls fetch '/api/candidate/5/responses' to populate data for UI

Let me know if anyone has insight or experience with a more effective/efficient solution for this issue

**Comment by wsbuck** [comment]
We merged a PR #181 yesterday that resolves this when frontend is using the dev server during development. I agree with Tyler that the production issue can be resolved by having Nginx forward missing routes to index.html or flask can probably solve that too.

I think the code for nginx is 
`location / {
    try_files $uri $uri/ /index.html;
}
`

or wherever our index.html file is.
